**Natural Language Pipeline and Text Processing**

![image.png](https://media.geeksforgeeks.org/wp-content/uploads/20250709120503764925/Text-Processing-21.webp)

**Data Collection**

In [ ]:
#install google play scrapper
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.2 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
#import library
from google_play_scraper import reviews, Sort
import pandas as pd

In [ ]:
result, continuation_token = reviews(
    'jp.konami.pesam',   # ganti dengan app id
    lang='en',              # ganti dengan bahasa
    # country='id',           # ganti dengan negara
    sort=Sort.NEWEST,       # review terbaru
    count=100              # jumlah review
)

In [ ]:
#ubah jadi bentuk dataframe
result_df = pd.DataFrame(result)
result_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8dbbc470-3fd1-4ec0-a2e6-6d6eca637a82,asif Official,https://play-lh.googleusercontent.com/a-/ALV-U...,Good But........... I Need Ronaldo & Nymar🥲,5,0,10.3.0,2026-03-01 07:52:47,None,None,10.3.0
1,6f740e22-9992-4fe0-b4e7-930f2dbf6ed1,Iskandar Juraimi,https://play-lh.googleusercontent.com/a/ACg8oc...,it is better then the fc mobile,4,0,10.3.0,2026-03-01 07:43:53,None,None,10.3.0
2,ef058e06-d0ba-4750-94af-6689bdb8967e,Erick John,https://play-lh.googleusercontent.com/a/ACg8oc...,I think Ronaldo 110 should now come,5,0,10.3.0,2026-03-01 07:43:23,None,None,10.3.0
3,b40bcb87-96de-4739-83d3-b08bd2f52f68,Kelvin Gichuki,https://play-lh.googleusercontent.com/a-/ALV-U...,best experience,4,0,10.3.0,2026-03-01 07:43:00,None,None,10.3.0
4,0d9d1cb7-c830-4157-ac6c-51e25ceac8c8,farzeenvengara,https://play-lh.googleusercontent.com/a/ACg8oc...,evrithing all so good game my opinion,5,0,10.3.0,2026-03-01 07:42:48,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,962664a7-568c-447b-8c4a-0c0d8f3c91ab,Otf Palampa,https://play-lh.googleusercontent.com/a/ACg8oc...,nice to play,5,0,10.3.0,2026-03-01 03:49:22,None,None,10.3.0
96,eb5899d0-1e4e-40b4-a444-fd767c2425f8,Daniel kwaku newel Oppong,https://play-lh.googleusercontent.com/a/ACg8oc...,"Efootball company, work on this issue for us. ...",5,0,10.3.0,2026-03-01 03:47:43,None,None,10.3.0
97,a74fc830-9d12-4487-991a-dd5538727ba4,Zenab,https://play-lh.googleusercontent.com/a/ACg8oc...,eFootball is the fastest and smoothest footbal...,5,0,None,2026-03-01 03:43:54,None,None,None
98,71b4fd91-ae56-47ff-bb60-e8b16577d839,Rina Datsa,https://play-lh.googleusercontent.com/a/ACg8oc...,indeed one of the 👌,5,0,None,2026-03-01 03:41:26,None,None,None
99,a85d43e5-a99c-4040-9a52-221efd303f1b,Mamata Shrestha,https://play-lh.googleusercontent.com/a/ACg8oc...,this game is scripted don't play this game thi...,1,0,10.3.0,2026-03-01 03:39:59,None,None,10.3.0

In [ ]:
df = result_df.copy()
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8dbbc470-3fd1-4ec0-a2e6-6d6eca637a82,asif Official,https://play-lh.googleusercontent.com/a-/ALV-U...,Good But........... I Need Ronaldo & Nymar🥲,5,0,10.3.0,2026-03-01 07:52:47,None,None,10.3.0
1,6f740e22-9992-4fe0-b4e7-930f2dbf6ed1,Iskandar Juraimi,https://play-lh.googleusercontent.com/a/ACg8oc...,it is better then the fc mobile,4,0,10.3.0,2026-03-01 07:43:53,None,None,10.3.0
2,ef058e06-d0ba-4750-94af-6689bdb8967e,Erick John,https://play-lh.googleusercontent.com/a/ACg8oc...,I think Ronaldo 110 should now come,5,0,10.3.0,2026-03-01 07:43:23,None,None,10.3.0
3,b40bcb87-96de-4739-83d3-b08bd2f52f68,Kelvin Gichuki,https://play-lh.googleusercontent.com/a-/ALV-U...,best experience,4,0,10.3.0,2026-03-01 07:43:00,None,None,10.3.0
4,0d9d1cb7-c830-4157-ac6c-51e25ceac8c8,farzeenvengara,https://play-lh.googleusercontent.com/a/ACg8oc...,evrithing all so good game my opinion,5,0,10.3.0,2026-03-01 07:42:48,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,962664a7-568c-447b-8c4a-0c0d8f3c91ab,Otf Palampa,https://play-lh.googleusercontent.com/a/ACg8oc...,nice to play,5,0,10.3.0,2026-03-01 03:49:22,None,None,10.3.0
96,eb5899d0-1e4e-40b4-a444-fd767c2425f8,Daniel kwaku newel Oppong,https://play-lh.googleusercontent.com/a/ACg8oc...,"Efootball company, work on this issue for us. ...",5,0,10.3.0,2026-03-01 03:47:43,None,None,10.3.0
97,a74fc830-9d12-4487-991a-dd5538727ba4,Zenab,https://play-lh.googleusercontent.com/a/ACg8oc...,eFootball is the fastest and smoothest footbal...,5,0,None,2026-03-01 03:43:54,None,None,None
98,71b4fd91-ae56-47ff-bb60-e8b16577d839,Rina Datsa,https://play-lh.googleusercontent.com/a/ACg8oc...,indeed one of the 👌,5,0,None,2026-03-01 03:41:26,None,None,None
99,a85d43e5-a99c-4040-9a52-221efd303f1b,Mamata Shrestha,https://play-lh.googleusercontent.com/a/ACg8oc...,this game is scripted don't play this game thi...,1,0,10.3.0,2026-03-01 03:39:59,None,None,10.3.0

In [ ]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [ ]:
#lihat kolom konten
df['content'].head(50)

0                                                                                                                                                                                                                                                                                                                                      Good But........... I Need Ronaldo & Nymar🥲
1                                                                                                                                                                                                                                                                                                                                                  it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                              I think Ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                                  best experience
4                                                                                                                                                                                                                                                                                                                                            evrithing all so good game my opinion
5                                                                                                                                               I love the game it make me happy but one issues is when I want to use my coins to spin player they always give me the the wrong player and I am from Japan I was born in Japan Konami please give me good players that when I spin
6                                                                                                                                                                                                                                                                                                                                                                       scam packs
7                                                                                                                                                                                                                                                                      stupid game,someone using cheat,so stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                             all I can say is wow
9                                                                                                                                                                                                                                                                                                                    game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                              this game was excellent record but some things are disturbing like the unstable server ,game glicz
11                                                                                                                                                                                                                                                                       im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                                          is ok just try and see
13                                                                                                                                                                                                                                                                                                                                   Konami bokachoda rendir chele from Bangladesh
14                                                                                                                                                                                                                                                                                                       konami tor ma ke chudi sala suorer bacha tor make ulto kore from Pakistan
15                                                                                                                                                                                                                                                                                                                                                                 SUPER eFOOTBAll
16                                                                                                                                                                                                                                                                                                                                                                      e football
17                                                                                                                                                                                                                                                                                    very good game. yayayayaya I like it. it's Enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                                    nice game 🎯👍
19                                                                                                                                                                                                                                                                                                                                                                         love it
20                                                                                                                                                                                                                        Sincerely speaking , konami remove smart assist from your game , simply the game promotes cheating in matches with opponents not playing fair and square
21    This game has become completely pay-to-win. For almost 11 months never received a single Epic or Big Time card, while paid players easily build top squads. Old Epic cards were even downgraded, which feels unfair and disrespectful. Weekly rewards are too low to matter, and gameplay often feels scripted. Skill no longer matters—only money does. Very disappointing.
22                                                                                                                                                                                                                                                                                                                             The game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                                         LOVE YOU TOO SWEETHEART
24                                                                                                                                                                                                                                                                                                                                                                     freestyle!!
25                                                                                                                                                                                                                                                                                                                                                                    this is nice
26                                                                                                                                                                                                                                                                                                    I hated this app because I tried to download it when it reaches 80% it stops
27                                                                                                                                                                                                                                                                                                                                                        just so perfect 💯💯❤️❤️🥳🥰
28                                                                                                                                                                                                                                                                                                                                                   voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                                   supporting ai not the players
30                                                                                                                                                                                                                                                                                                                      I've been playing this game for 4 years now this game is 💩
31                                                                                                                                                                                                                                                                                                                                      a good experience with e football,try it❤️
32                                                                                                                                                                                                                                                                                                it is a good game with brilliant graphics i really love 💕💕 the game very much it
33                                                                                                                                                                                                                                                                                                               this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                            good
35                                                                                                                                                                                                                                                                                                                                CABDIQADIR ROOBLR MAXAMUUS MAREXAN COLOW SHAMAKE
36                                                                                                                                                                                                                                                                                                                                                                      game rusak
37                                                                                                                                                                                                                                                                                                                  نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                                          why always unfinished game when I play with my friend?
39                                                                                                                                                                                                                                                                                    It's a good game is 👍, it's just that you need to show us how to do some dribbles and skills
40                    game anj, pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya. mohon segera perbaiki lah Konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                                        efootball is the best unlike fc mobile .
42                                                                                                                                                                                                                                                                                                                                                           you want to reduce GB
43                                                                                                                                                                                                                                                                                                                                                                        so fun 😊
44                                                                                                                                                                                                                                                                                                                                                                  Very nice game
45                                                                                                                                         hey konami, please fix lagging issues while playing pvp/division. I encountered many lagging even though I'm using WiFi already. please fix your server asap. I'm done with this game if you guys aren't doing well with server issues.
46                                                                                                                                                                                                                                                                                                                                                                       very nice
47                                                                                                                                                                                                                                                                                                                                                                  Best game ever
48                                                                                                                                                                                                                                                                                                                                                                            best
49                                                                                                                                                                                                                                                                                                               This game is so nice 🙂👍 I can take a hole day playing this game 🎮
Name: content, dtype: object

In [ ]:
#masukan kolom content ke dalam variabel baru
data_cleaning = df['content']
data_cleaning.head(30)

0     every time there is one problem with this game why?, why do you guys interfere with the games, you favour a particular team over the other every single game, a lot of people are experiencing this, deny all you want it's true!, if you claim it isn't the management then definitely there is something wrong with your system, favoritism on a whole new level, defenders making mistakes, slow passes from midfielders, slow run from high pace strikers, BASICALLY THRASH, I am on the receiving end, FIX IT!
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Konami is the best the football game ever is efootball
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Uman
3                                                                                                                                                                                                                                                                                                                    I love this game but Konami please in your next update make sure you make it possible to transfer players from different account to another. If it is added l would able to make your review 5 stars
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               pes 2022?
5                                                                                                                                                                                                                                                                                                                                                                                                                                         babi konami. spin player tak pernah ada luck bangang betul. Very stupid konami.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                the substitutions is not seen as compared with Fc mobile
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               like thid
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        i love this game
9                                                                                                                                                                                                                                                                                                                                                                                                          The script is too much bro we're tired man you can do better please. the division is so manipulating bro 🤦‍♂️💔
10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Perfect best football game
11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              best game
12                                                                                                                                                                                                                                                                                                            Give fede valverde his long socks. and for the next major update for the new season in August surprise us with new goal post nets. And by the way the game is top notch honestly 👌 my favorite i love it.❤️
13                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     the best game ever
14                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               optional
15                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
16                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             efootball is the best game
17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Nice 😀
18                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   wow!
19                                                                                                                                                                                                                                                                                                                                                                                                                     Its a good game but they should give us more opertonities to gather more coins and valuable awards
20                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     😊😊
21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            لعبة ممتازة
22                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             great game
23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   nice
24                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     words won't explain this good game
25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              very good
26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   good
27                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Best
28                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       when there is Neymar there's fun
29                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  best game of the year
Name: content, dtype: object

**Lowercasing**

In [ ]:
df['content_clean'] = df['content'].str.lower()
df['content_clean'].head(50)

0                                                                                                                                                                                                                                                                                                                                      good but........... i need ronaldo & nymar🥲
1                                                                                                                                                                                                                                                                                                                                                  it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                              i think ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                                  best experience
4                                                                                                                                                                                                                                                                                                                                            evrithing all so good game my opinion
5                                                                                                                                               i love the game it make me happy but one issues is when i want to use my coins to spin player they always give me the the wrong player and i am from japan i was born in japan konami please give me good players that when i spin
6                                                                                                                                                                                                                                                                                                                                                                       scam packs
7                                                                                                                                                                                                                                                                      stupid game,someone using cheat,so stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                             all i can say is wow
9                                                                                                                                                                                                                                                                                                                    game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                              this game was excellent record but some things are disturbing like the unstable server ,game glicz
11                                                                                                                                                                                                                                                                       im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                                          is ok just try and see
13                                                                                                                                                                                                                                                                                                                                   konami bokachoda rendir chele from bangladesh
14                                                                                                                                                                                                                                                                                                       konami tor ma ke chudi sala suorer bacha tor make ulto kore from pakistan
15                                                                                                                                                                                                                                                                                                                                                                 super efootball
16                                                                                                                                                                                                                                                                                                                                                                      e football
17                                                                                                                                                                                                                                                                                    very good game. yayayayaya i like it. it's enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                                    nice game 🎯👍
19                                                                                                                                                                                                                                                                                                                                                                         love it
20                                                                                                                                                                                                                        sincerely speaking , konami remove smart assist from your game , simply the game promotes cheating in matches with opponents not playing fair and square
21    this game has become completely pay-to-win. for almost 11 months never received a single epic or big time card, while paid players easily build top squads. old epic cards were even downgraded, which feels unfair and disrespectful. weekly rewards are too low to matter, and gameplay often feels scripted. skill no longer matters—only money does. very disappointing.
22                                                                                                                                                                                                                                                                                                                             the game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                                         love you too sweetheart
24                                                                                                                                                                                                                                                                                                                                                                     freestyle!!
25                                                                                                                                                                                                                                                                                                                                                                    this is nice
26                                                                                                                                                                                                                                                                                                    i hated this app because i tried to download it when it reaches 80% it stops
27                                                                                                                                                                                                                                                                                                                                                        just so perfect 💯💯❤️❤️🥳🥰
28                                                                                                                                                                                                                                                                                                                                                   voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                                   supporting ai not the players
30                                                                                                                                                                                                                                                                                                                      i've been playing this game for 4 years now this game is 💩
31                                                                                                                                                                                                                                                                                                                                      a good experience with e football,try it❤️
32                                                                                                                                                                                                                                                                                                it is a good game with brilliant graphics i really love 💕💕 the game very much it
33                                                                                                                                                                                                                                                                                                               this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                            good
35                                                                                                                                                                                                                                                                                                                                cabdiqadir rooblr maxamuus marexan colow shamake
36                                                                                                                                                                                                                                                                                                                                                                      game rusak
37                                                                                                                                                                                                                                                                                                                  نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                                          why always unfinished game when i play with my friend?
39                                                                                                                                                                                                                                                                                    it's a good game is 👍, it's just that you need to show us how to do some dribbles and skills
40                    game anj, pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya. mohon segera perbaiki lah konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                                        efootball is the best unlike fc mobile .
42                                                                                                                                                                                                                                                                                                                                                           you want to reduce gb
43                                                                                                                                                                                                                                                                                                                                                                        so fun 😊
44                                                                                                                                                                                                                                                                                                                                                                  very nice game
45                                                                                                                                         hey konami, please fix lagging issues while playing pvp/division. i encountered many lagging even though i'm using wifi already. please fix your server asap. i'm done with this game if you guys aren't doing well with server issues.
46                                                                                                                                                                                                                                                                                                                                                                       very nice
47                                                                                                                                                                                                                                                                                                                                                                  best game ever
48                                                                                                                                                                                                                                                                                                                                                                            best
49                                                                                                                                                                                                                                                                                                               this game is so nice 🙂👍 i can take a hole day playing this game 🎮
Name: content_clean, dtype: object

hapus tanda baca

In [ ]:
df['content_clean'].str.strip()

0                                                                             good but i need ronaldo  nymar
1                                                                            it is better then the fc mobile
2                                                                        i think ronaldo 110 should now come
3                                                                                            best experience
4                                                                      evrithing all so good game my opinion
                                                       ...
95                                                                                              nice to play
96    efootball company work on this issue for us for the goalkeeper it must be cleaansheet not goals please
97                      efootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                         indeed one of the
99                                  this game is scripted dont play this game this game is too bad fc better
Name: content_clean, Length: 100, dtype: object

In [ ]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-152/4156829393.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

0                                                                                                                                                                                                                                                                                                                                       good but i need ronaldo  nymar
1                                                                                                                                                                                                                                                                                                                                      it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                  i think ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                      best experience
4                                                                                                                                                                                                                                                                                                                                evrithing all so good game my opinion
5                                                                                                                                   i love the game it make me happy but one issues is when i want to use my coins to spin player they always give me the the wrong player and i am from japan i was born in japan konami please give me good players that when i spin
6                                                                                                                                                                                                                                                                                                                                                           scam packs
7                                                                                                                                                                                                                                                            stupid gamesomeone using cheatso stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                 all i can say is wow
9                                                                                                                                                                                                                                                                                                        game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                   this game was excellent record but some things are disturbing like the unstable server game glicz
11                                                                                                                                                                                                                                                           im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                              is ok just try and see
13                                                                                                                                                                                                                                                                                                                       konami bokachoda rendir chele from bangladesh
14                                                                                                                                                                                                                                                                                           konami tor ma ke chudi sala suorer bacha tor make ulto kore from pakistan
15                                                                                                                                                                                                                                                                                                                                                     super efootball
16                                                                                                                                                                                                                                                                                                                                                          e football
17                                                                                                                                                                                                                                                                           very good game yayayayaya i like it its enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                          nice game
19                                                                                                                                                                                                                                                                                                                                                             love it
20                                                                                                                                                                                                              sincerely speaking  konami remove smart assist from your game  simply the game promotes cheating in matches with opponents not playing fair and square
21    this game has become completely paytowin for almost 11 months never received a single epic or big time card while paid players easily build top squads old epic cards were even downgraded which feels unfair and disrespectful weekly rewards are too low to matter and gameplay often feels scripted skill no longer mattersonly money does very disappointing
22                                                                                                                                                                                                                                                                                                                 the game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                             love you too sweetheart
24                                                                                                                                                                                                                                                                                                                                                           freestyle
25                                                                                                                                                                                                                                                                                                                                                        this is nice
26                                                                                                                                                                                                                                                                                         i hated this app because i tried to download it when it reaches 80 it stops
27                                                                                                                                                                                                                                                                                                                                                    just so perfect
28                                                                                                                                                                                                                                                                                                                                       voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                       supporting ai not the players
30                                                                                                                                                                                                                                                                                                            ive been playing this game for 4 years now this game is
31                                                                                                                                                                                                                                                                                                                             a good experience with e footballtry it
32                                                                                                                                                                                                                                                                                      it is a good game with brilliant graphics i really love  the game very much it
33                                                                                                                                                                                                                                                                                                   this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                good
35                                                                                                                                                                                                                                                                                                                    cabdiqadir rooblr maxamuus marexan colow shamake
36                                                                                                                                                                                                                                                                                                                                                          game rusak
37                                                                                                                                                                                                                                                                                                      نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                               why always unfinished game when i play with my friend
39                                                                                                                                                                                                                                                                            its a good game is  its just that you need to show us how to do some dribbles and skills
40          game anj pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya mohon segera perbaiki lah konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                             efootball is the best unlike fc mobile
42                                                                                                                                                                                                                                                                                                                                               you want to reduce gb
43                                                                                                                                                                                                                                                                                                                                                             so fun
44                                                                                                                                                                                                                                                                                                                                                      very nice game
45                                                                                                                                      hey konami please fix lagging issues while playing pvpdivision i encountered many lagging even though im using wifi already please fix your server asap im done with this game if you guys arent doing well with server issues
46                                                                                                                                                                                                                                                                                                                                                           very nice
47                                                                                                                                                                                                                                                                                                                                                      best game ever
48                                                                                                                                                                                                                                                                                                                                                                best
49                                                                                                                                                                                                                                                                                                      this game is so nice  i can take a hole day playing this game
Name: content_clean, dtype: object

**Remove Punctuation**

In [ ]:
df['content_clean'].str.replace('[^\w\s]','',regex=True)

**Masukan ke dalam satu fungsi**

In [ ]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-152/1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [ ]:
df = clean_data(df, 'content')

print(df[['content', 'content_clean']])

                                                                                                        content  \
0                                                                   Good But........... I Need Ronaldo & Nymar🥲
1                                                                               it is better then the fc mobile
2                                                                           I think Ronaldo 110 should now come
3                                                                                               best experience
4                                                                         evrithing all so good game my opinion
..                                                                                                          ...
95                                                                                                 nice to play
96  Efootball company, work on this issue for us. For the goalkeeper, it must be cleaansheet, not goals, please
97                         eFootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                          indeed one of the 👌
99                                    this game is scripted don't play this game this game is too bad fc better

                                                                                             content_clean
0                                                                           good but i need ronaldo  nymar
1                                                                          it is better then the fc mobile
2                                                                      i think ronaldo 110 should now come
3                                                                                          best experience
4                                                                    evrithing all so good game my opinion
..                                                                                                     ...
95                                                                                            nice to play
96  efootball company work on this issue for us for the goalkeeper it must be cleaansheet not goals please
97                    efootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                      indeed one of the
99                                this game is scripted dont play this game this game is too bad fc better

[100 rows x 2 columns]

**Penggunaan library Spacy untuk text processing**

In [ ]:
#import library spacy
import spacy

In [ ]:
#load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[1, 'content_clean']
phrase

'it is better then the fc mobile'

In [ ]:
doc = nlp(phrase)
doc

it is better then the fc mobile

**Tokenization**

In [ ]:
[token for token in doc]

[it, is, better, then, the, fc, mobile]

**Lemmatization**

In [ ]:
[token.lemma_ for token in doc if not token.is_stop]

['well', 'fc', 'mobile']

**Stop Word**

In [ ]:
list(nlp.Defaults.stop_words)[:10000]

['empty',
 'must',
 '‘m',
 'twenty',
 'between',
 '‘d',
 'myself',
 'ourselves',
 'i',
 'mostly',
 'sometime',
 'except',
 'that',
 'nowhere',
 'former',
 'therefore',
 'whom',
 'used',
 'yourselves',
 'around',
 'put',
 'using',
 'would',
 'twelve',
 'whole',
 'through',
 'wherein',
 'call',
 'does',
 'none',
 'meanwhile',
 'please',
 'both',
 'yourself',
 'namely',
 'throughout',
 'his',
 'only',
 'below',
 'under',
 'beyond',
 'her',
 'been',
 'off',
 'then',
 'mine',
 'bottom',
 'own',
 'or',
 'will',
 'can',
 'your',
 'too',
 'somewhere',
 'next',
 'via',
 'although',
 'n‘t',
 'go',
 'in',
 'there',
 'beforehand',
 'seemed',
 'some',
 'them',
 'to',
 'about',
 'a',
 'several',
 'us',
 'so',
 'if',
 'same',
 'thereafter',
 'first',
 'within',
 'its',
 "n't",
 'she',
 'whereafter',
 'during',
 'again',
 'keep',
 'part',
 'into',
 "'re",
 'after',
 'of',
 'indeed',
 'it',
 'four',
 'down',
 'should',
 'here',
 'their',
 'might',
 'further',
 "'s",
 '’ll',
 'moreover',
 'enough',
 'make',
 'hundred',
 'many',
 'seems',
 'may',
 'me',
 'however',
 'even',
 'these',
 'becomes',
 'this',
 'yours',
 'whereas',
 'such',
 'six',
 'over',
 'was',
 'anyone',
 'due',
 'anyway',
 'became',
 'how',
 'our',
 "'ve",
 'have',
 'rather',
 'always',
 'thru',
 'anywhere',
 'above',
 'hence',
 'say',
 'those',
 'yet',
 'give',
 'see',
 'with',
 'being',
 'were',
 'whatever',
 'along',
 'at',
 'more',
 'herein',
 'nine',
 'themselves',
 'per',
 '’ve',
 'against',
 'also',
 'which',
 'two',
 'amongst',
 'well',
 'they',
 'no',
 '’m',
 'top',
 'never',
 'from',
 'ours',
 'regarding',
 'whether',
 'fifteen',
 'last',
 'something',
 'nevertheless',
 'across',
 'onto',
 'doing',
 'take',
 'least',
 'forty',
 '’s',
 'because',
 'without',
 'much',
 'hereupon',
 'each',
 'afterwards',
 'almost',
 'whereupon',
 'since',
 'every',
 'side',
 'while',
 'had',
 'amount',
 'often',
 'someone',
 'could',
 'whoever',
 'latter',
 'who',
 "'m",
 'nobody',
 'and',
 'before',
 'thereby',
 'an',
 'seem',
 'we',
 'elsewhere',
 'whence',
 'less',
 'quite',
 'thereupon',
 'one',
 'anyhow',
 '’d',
 'nor',
 'whereby',
 'eight',
 'thence',
 'wherever',
 'upon',
 'hereafter',
 'as',
 'formerly',
 'than',
 'when',
 'three',
 'all',
 'just',
 'third',
 'whenever',
 'cannot',
 'for',
 'latterly',
 'until',
 'sixty',
 'somehow',
 'up',
 '‘ve',
 'once',
 'few',
 'therein',
 'alone',
 'hereby',
 'already',
 'ever',
 'you',
 'becoming',
 '‘re',
 '’re',
 'either',
 'name',
 'toward',
 'ten',
 'besides',
 'noone',
 'very',
 'seeming',
 'other',
 'show',
 'are',
 'the',
 'made',
 'out',
 'another',
 'get',
 'perhaps',
 'else',
 'together',
 'my',
 'but',
 'not',
 "'d",
 'ca',
 "'ll",
 '‘ll',
 'everything',
 'is',
 'back',
 'done',
 'sometimes',
 'herself',
 'full',
 'he',
 'otherwise',
 'among',
 'front',
 'him',
 'on',
 'others',
 'though',
 'serious',
 'whose',
 'by',
 'what',
 'nothing',
 'do',
 'still',
 'now',
 'hers',
 '‘s',
 'various',
 'fifty',
 'towards',
 'beside',
 'any',
 'neither',
 'become',
 'really',
 'unless',
 'itself',
 'behind',
 'five',
 'n’t',
 'everyone',
 'move',
 'himself',
 'everywhere',
 'am',
 'thus',
 're',
 'where',
 'did',
 'eleven',
 'most',
 'be',
 'has',
 'anything',
 'whither',
 'why']